[package]
name = "cli"
version = "0.0.1"
authors = ["Masayuki Takeda <mtakeda.enigsol@gmail.com>"]
edition = "2018"

[dependencies]
tobiuo = { path = "../tobiuo" }
docopt = "1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
